server:
  port: ${PORT:8888}
  ssl:
    enabled: true
    key-store: classpath:config_server2.jks
    key-store-password: password
    key-alias: config-server
    key-store-type: JKS
    trust-store: classpath:config_server_truststore.jks
    trust-store-password: password
    trust-store-type: JKS
    client-auth: want

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri : https://github.com/NatasaLukic/spring-cloud-config-repo.git

eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    #prefer-ip-address: true
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: https://${eureka.instance.hostname}:${server.port}
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
  client:
    enabled: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone:  ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:https://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

ribbon:
  eureka:
    enabled: true

