server:
  ssl:
    enabled: true
    protocol: TLS
    key-store: classpath:bankacq2.jks
    key-store-password: bankacq
    key-password: bankacq
    keyStoreType: JKS
    keyAlias: bankacq
    trust-store: classpath:bankacq_truststore.jks
    trust-store-password: bankacq
    trust-store-type: JKS
    
spring:
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN