server:
  port: 8447
  ssl:
    enabled: true
    key-store: classpath:luservice2.jks
    key-store-password: luservice
    key-alias: literary.association(localhost)
    key-store-type: JKS
    trust-store: classpath:luservice_truststore.jks
    trust-store-password: password
    trust-store-type: JKS
    client-auth: want