server:
  port: ${PORT:8762}
  ssl:
    enabled: true
    protocol: TLS
    key-store: classpath:gateway.jks
    key-store-password: gateway
    key-password: gateway
    keyStoreType: JKS
    keyAlias: gateway
    trust-store: classpath:gateway_truststore.jks
    trust-store-password: gateway
    trust-store-type: JKS
    client-auth: want

spring:
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN

management:
  endpoints:
    web:
      exposure:
        include=*:

eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    #prefer-ip-address: true
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: https://${eureka.instance.hostname}:${server.port}
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
  client:
    enabled: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone:  ${EUREKA_URI:https://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 240000

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000