server:
  port: ${PORT:8762}
  ssl:
    enabled: true
    protocol: TLS
    key-store: classpath:gateway.jks
    key-store-password: gateway
    key-password: gateway
    keyStoreType: JKS
    keyAlias: gateway
    trust-store: classpath:gateway_truststore.jks
    trust-store-password: gateway
    trust-store-type: JKS
    client-auth: want

management:
  endpoints:
    web:
      exposure:
        include=*:

eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    #prefer-ip-address: true
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: https://${eureka.instance.hostname}:${server.port}
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
  client:
    enabled: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone:  ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:https://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000



