server:
  port: ${PORT:8762}
  ssl:
    enabled: true
    key-store: classpath:gateway.jks
    key-store-password: password
    key-alias: gateway   
security:
  require-ssl: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/ 
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    gateway:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  ribbon:
    IsSecured: true
    ConnectTimeout:  10000
    ReadTimeout:  10000
    eureka:
      enabled: true
    TrustStore: classpath:gateway.jks
    TrustStorePassword : password
    IsHostnameValidationRequired: false
