server:
  port: ${PORT:8888}
  ssl:
    enabled: true
    key-store: classpath:config_server.jks
    key-store-password: password
    key-alias: config-server
    key-store-type: JKS
    trust-store: classpath:config_server_truststore.jks
    trust-store-password: password
    trust-store-type: JKS
    client-auth: want

spring:
  application:
    name: config-server
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
  cloud:
    config:
      server:
        git:
          uri : https://github.com/NatasaLukic/spring-cloud-config-repo.git

eureka:
  instance:
    #hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    prefer-ip-address: true
    statusPageUrl: https://localhost:${server.port}/info
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
  client:
    enabled: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone:  ${EUREKA_URI:https://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

ribbon:
  eureka:
    enabled: true

