version: "3.3"
services:

  db:
    image: mysql
    container_name: upp_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: upp_db
    ports:
      - 3307:3306

  camunda:
    image: camunda/camunda-bpm-platform:latest
    container_name: camunda
    ports:
      - 8081:8080
    restart: unless-stopped
