server:
  port: ${PORT:8443}
  ssl:
    enabled: true
    protocol: TLS
    key-store: classpath:paypal2.jks
    key-store-password: paypal
    key-password: paypal
    keyStoreType: JKS
    keyAlias: paypal-ms
    trust-store: classpath:paypal_truststore.jks
    trust-store-password: paypal
    trust-store-type: JKS
    client-auth: want


eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    #prefer-ip-address: true
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: https://${eureka.instance.hostname}:${server.port}
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
  client:
    enabled: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone:  ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:https://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

execution:
  mode: sandbox

success:
  url_agreement : https://${eureka.instance.hostname}:8443/subscriptions/complete?subscriptionId=

cancel:
  url_agreement : https://${eureka.instance.hostname}:8443/subscriptions/cancel?subscriptionId=
