server:
  port: 8761
#  ssl:
#    enabled: true
#    protocol: TLS
#    key-store: classpath:discovery.p12
#    key-store-password: discovery
#    key-password: discovery
#    keyStoreType: PKCS12
#    keyAlias: discovery
#    trust-store: classpath:discovery.p12
#    trust-store-password: discovery
#    client-auth: want

spring:
  application:
    name: containerized-discovery

eureka:
  instance:
    statusPageUrl: https://localhost:${server.port}/info
    prefer-ip-address: true
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000