server:
  port: 8761
  ssl:
    enabled: true
    client-auth: want
    key-store: classpath:discovery.jks
    key-store-password: password
    key-alias: discovery
    trust-store: classpath:discovery.jks
    trust-store-password: password


eureka:
  instance:
    securePort: ${server.port}
    securePortEnabled: true
    prefer-ip-address: true
    nonSecurePortEnabled: false 
  client:
    registerWithEureka: false
    fetchRegistry: false
