server:
  port: 8761
  ssl:
    enabled: true
    protocol: TLS
    key-store: classpath:discovery.jks
    key-store-password: password
    key-password: password
    keyStoreType: JKS
    keyAlias: discovery
    client-auth: want


eureka:
  instance:
    statusPageUrl: http://localhost:${server.port}/info
    prefer-ip-address: true
    healthCheckUrl: http://localhost:${server.port}/health
    homePageUrl: http://localhost:${server.port}
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
