server:
  port: ${PORT:8444}
  ssl:
    enabled: true
    protocol: TLS
    key-store: classpath:paymentinfo.jks
    key-store-password: paymentinfo
    key-password: paymentinfo
    keyStoreType: JKS
    keyAlias: payment-info
    trust-store: classpath:paymentinfo_truststore.jks
    trust-store-password: paymentinfo
    trust-store-type: JKS
    client-auth: want

spring:
    logging:
        pattern:
            console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
        level:
            org.springframework: WARN
            org.hibernate: WARN

eureka:
  instance:
    #hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    prefer-ip-address: true
    statusPageUrl: https://localhost:${server.port}/info
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
  client:
    enabled: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone:  ${EUREKA_URI:https://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

ribbon:
  eureka:
    enabled: true
