server:
  port: ${PORT:8444}
  ssl:
    enabled: true
    protocol: TLS
    key-store: classpath:paymentinfo2.jks
    key-store-password: paymentinfo
    key-password: paymentinfo
    keyStoreType: JKS
    keyAlias: payment-info
    trust-store: classpath:paymentinfo_truststore.jks
    trust-store-password: paymentinfo
    trust-store-type: JKS
    client-auth: want


eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    #prefer-ip-address: true
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: https://${eureka.instance.hostname}:${server.port}
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
  client:
    enabled: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone:  ${EUREKA_URI:https://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

